### ISSUE TITLE
请问这个loss，是如何做到监督的？

### ISSUE THREAD

**Issue by EricLingRui** [vdogmcgee/SimCSE-Chinese-Pytorch#1]
https://github.com/vdogmcgee/SimCSE-Chinese-Pytorch/blob/011e4b2de8b6e057b76ae4047f1818696e10261d/simcse_sup.py#L135
看了半天也没看出来label是怎么被监督的？
tokenizer那，batch第三个是label，这里第三个又直接剃掉，默认每组样本对的标签都为1？
有些样本对在STS-B中，为0（负样本）的哇~

**Comment by vdogmcgee** [comment]
有监督是用数据集给定的相似样本作为正样本，在损失函数中去计算batch的相似度矩阵， 跟真实的正样本标签索引数组作交叉熵，这样达到有监督的效果。 

有监督训练用的是SNIL，三个样本为一对，我自己理解是每第三个样本它自己没有对应的正样本，所以他只能作为其他句子的负样本，所以在这里做了一个select，如果对于一句话有困难样本，放在第三个效果应该会更好，但是我目前没有这样的数据集。

验证用的是STS-B，0-5的相似度打分只作为了模型评估。

**Comment by EricLingRui** [comment]
> 有监督是用数据集给定的相似样本作为正样本，在损失函数中去计算batch的相似度矩阵， 跟真实的正样本标签索引数组作交叉熵，这样达到有监督的效果。
> 
> 有监督训练用的是SNIL，三个样本为一对，我自己理解是每第三个样本它自己没有对应的正样本，所以他只能作为其他句子的负样本，所以在这里做了一个select，如果对于一句话有困难样本，放在第三个效果应该会更好，但是我目前没有这样的数据集。
> 
> 验证用的是STS-B，0-5的相似度打分只作为了模型评估。

明白了，感谢回答。

**Comment by crystal0913** [comment]
> https://github.com/vdogmcgee/SimCSE-Chinese-Pytorch/blob/011e4b2de8b6e057b76ae4047f1818696e10261d/simcse_sup.py#L135
> 
> 
> 看了半天也没看出来label是怎么被监督的？
> tokenizer那，batch第三个是label，这里第三个又直接剃掉，默认每组样本对的标签都为1？
> 有些样本对在STS-B中，为0（负样本）的哇~

作者是对原始的snli数据集做了一定预处理，使用`data_preprocess.py`, batch里面第3个并不是label了，变成了这种格式：line['origin'], line['entailment'], line['contradiction']
