### ISSUE TITLE
simcse_unsup_loss 中没有  l2_normalize 操作，是否有必要加上？

### ISSUE THREAD

**Issue by liulinlin** [vdogmcgee/SimCSE-Chinese-Pytorch#14]
我看苏神在计算cosine_similarity 之前，首先对数据 进行了一次 l2_normalize  ，但是看您的代码中，没有这一步的操作，是否是特意这么处理的？

**Comment by vdogmcgee** [comment]
F.cosine_similarity 这个API 会自动先进行归一化
