### ISSUE TITLE
有监督的可以改用STS-B train数据集吗 

### ISSUE THREAD

**Issue by wanghai345** [vdogmcgee/SimCSE-Chinese-Pytorch#15]
有监督的可以改用STS-B train数据集吗

**Comment by wanghai345** [comment]
使用STS-B train 作为训练数据。但是比SNLI少一列 文本，是否可以呢？

**Comment by vdogmcgee** [comment]
可以的 , 但需要注意的是 , snli每一行都有一句正样本 , 但STS-B是打分制的 ,  要是选正样本的话 , 最好选语义相近 , 也就是 4分5分的

**Comment by wanghai345** [comment]
嗯，但是STS-B ，每行是两个文本，snli没行是三个文本，所以这要怎么处理呢，是不是需要将STS-b处理成 snli的形式。

**Comment by wanghai345** [comment]
我理解就是 如果使用STS-B作为训练数据，那么选取4分和5分的 语句放入 origin 和 entailment，然后 contradiction 设为空字符串来进行训练是吧。

**Comment by vdogmcgee** [comment]
对 , 用sts-B的数据集  , 不需要contradiction ,  改一下损失函数里面的正样本的 index 就行

**Comment by wanghai345** [comment]
好的，非常感谢！
