### ISSUE TITLE
关于README中预训练模型地址的问题

### ISSUE THREAD

**Issue by WangYizhang01** [vdogmcgee/SimCSE-Chinese-Pytorch#3]
你好，预训练模型下载地址好像有问题，缺少tokenizer相关文件。

**Comment by vdogmcgee** [comment]
你好, 看了下第一个bert的链接确实没有 vocab.txt , 可以网上搜一份, 或者直接下载后面的bert-wwm模型 , 那里面有

**Comment by WangYizhang01** [comment]
> 你好, 看了下第一个bert的链接确实没有 vocab.txt , 可以网上搜一份, 或者直接下载后面的bert-wwm模型 , 那里面有

是的，直接去hugging face的模型库中下载就行，我只是mark一下。
